name: Build and run tests
 
on: [push]
 
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [14, 15, 16]
    name: Java ${{ matrix.java }} run tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn --batch-mode clean test
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests  
